remove CoffeeScript dependencies and use vanilla JavaScript.
rakvium/taxi pull request #13
Opened 2016-10-04 13:02 UTC by DimaKaUA

2016-10-04 13:21 UTC, rakvium requested changes

2016-10-04 13:21 UTC, rakvium commented on Gemfile
> +# gem 'coffee-rails', '~> 4.1.0'
Don't comment, just remove.

2016-10-04 13:21 UTC, rakvium commented on app/views/layouts/application.html.erb
> -  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
Why did you remove these lines?

2016-10-04 13:23 UTC, DimaKaUA commented on Gemfile
> +# gem 'coffee-rails', '~> 4.1.0'
will be done

2016-10-04 13:29 UTC, DimaKaUA commented on app/views/layouts/application.html.erb
> -  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
if i understood correctly this code relates to coffeescript

2016-10-04 13:29 UTC, DimaKaUA commented on app/views/layouts/application.html.erb
> -  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
and it is not suitable now

2016-10-04 13:31 UTC, DimaKaUA commented on app/views/layouts/application.html.erb
> -  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
This caused an error)))

2016-10-04 13:34 UTC, rakvium commented on app/views/layouts/application.html.erb
> -  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
@DimaKaUA, no, it's just JavaScript.

2016-10-04 13:47 UTC, DimaKaUA commented on app/views/layouts/application.html.erb
> -  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
But it doesn't work after removal of gem "coffee-rails". I have not figured out with this

2016-10-04 15:47 UTC, rakvium requested changes

2016-10-04 15:47 UTC, rakvium commented on Gemfile
> +gem 'vanilla-ujs'
Are you serious? Remove this gem, just don't use any CoffeeScript.

2016-10-04 15:47 UTC, rakvium commented on app/views/layouts/application.html.erb
> -  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
Search for `coffee` in config files. Remove any inclusion of it.

2016-10-05 07:44 UTC, rakvium commented on app/assets/javascripts/application.js
>  // Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
Remove the `Coffee`, please :wink:

2016-10-05 08:54 UTC, rakvium requested changes

2016-10-05 08:54 UTC, rakvium commented on db/schema.rb
> -  create_table "dispatchers", force: :cascade do |t|
Please pull current master branch. We don't need to remove dispatchers :wink:

2016-10-05 10:57 UTC, rakvium requested changes

2016-10-05 10:57 UTC, rakvium commented on app/assets/javascripts/orders.js
> +# Place all the behaviors and hooks related to the matching controller here.
Please use JS comments :wink:

2016-10-05 11:37 UTC, rakvium requested changes

2016-10-05 11:37 UTC, rakvium commented on app/controllers/orders_controller.rb
> +
Redundant space

2016-10-06 13:58 UTC, rakvium approved these changes

2016-10-06 14:01 UTC, merged