commit for pull request
rakvium/taxi pull request #2
Opened 2016-10-04 08:16 UTC by SerjB

2016-10-04 08:27 UTC, rakvium requested changes
Please fix formatting issues (see my comments)

2016-10-04 08:27 UTC, rakvium commented on README.rdoc
> -
Please add Contributors header using Markdown: [https://guides.github.com/features/mastering-markdown/](url)

2016-10-04 08:27 UTC, rakvium commented on README.rdoc
> +serj.bichkhidzhy@gmail.com
Please move your email to the line with your name :construction_worker_man:

2016-10-04 08:51 UTC, SerjB commented
Done

2016-10-04 09:15 UTC, SerjB commented on README.rdoc
> +serj.bichkhidzhy@gmail.com
Done

2016-10-04 13:44 UTC, rakvium requested changes

2016-10-04 13:44 UTC, rakvium commented on README.rdoc
> +Serj_Bichkhidzhy 	serj.bichkhidzhy@gmail.com
@SerjB please add Contributors section above, like `## Contributors`.
Also please don't use tabs, spaces are more consistent.

2016-10-04 13:44 UTC, rakvium commented on app/models/application_record.rb
> +=======
Please remove unnecessary lines.

2016-10-04 14:02 UTC, rakvium commented on README.rdoc
> +Contributors.
Why there is a dot here?

2016-10-06 15:27 UTC, rakvium approved these changes

2016-10-06 15:28 UTC, rakvium requested changes

2016-10-06 15:28 UTC, rakvium commented on app/models/admin.rb
> +  devise :database_authenticatable, :registerable,
Admin shouldn't be registerable.

2016-10-07 08:37 UTC, rakvium approved these changes

2016-10-07 08:38 UTC, merged