Adding colomn to drivers
rakvium/taxi pull request #24
Opened 2016-10-10 13:45 UTC by SerjB

2016-10-10 17:19 UTC, rakvium requested changes

2016-10-10 17:19 UTC, rakvium commented on app/models/admin.rb
> +  devise :database_authenticatable, :registerable,
Why registerable?

2016-10-10 17:19 UTC, rakvium commented on app/views/layouts/application.html.erb
> +<%= link_to("Log out", destroy_dispatcher_session_path) %>
What if we have both driver and dispatcher logged in?

2016-10-10 17:19 UTC, rakvium commented on config/routes.rb
> +  devise_for :drivers,  :controllers => { registrations: 'registrations' }
Please use new Ruby hash literal syntax: https://github.com/bbatsov/ruby-style-guide#hash-literals

2016-10-11 07:49 UTC, bhkhdh commented on app/models/admin.rb
> +  devise :database_authenticatable, :registerable,
By the fact that the administrator can register another administrator, and if remove "regitrable", they can't do this.

2016-10-11 08:00 UTC, SerjB commented on app/views/layouts/application.html.erb
> +<%= link_to("Log out", destroy_dispatcher_session_path) %>
I I'm working on it

2016-10-11 08:02 UTC, bhkhdh commented on config/routes.rb
> +  devise_for :drivers,  :controllers => { registrations: 'registrations' }
It's doesn't working when i write 'registrations => 'registrations''. Main trget of this request is adding colomn :D

2016-10-11 10:15 UTC, rakvium commented on app/models/admin.rb
> +  devise :database_authenticatable, :registerable,
"Registerable" there means that any user can come and register himself as an admin. It's not an option.

2016-10-11 10:16 UTC, rakvium commented on app/views/layouts/application.html.erb
> +<%= link_to("Log out", destroy_dispatcher_session_path) %>
OK, just add ` as a dispatcher` to eliminate an ambiguity :relieved:

2016-10-11 10:17 UTC, rakvium commented on config/routes.rb
> +  devise_for :drivers,  :controllers => { registrations: 'registrations' }
There should be `controllers:`, not `:controllers =>`.

2016-10-11 10:18 UTC, rakvium requested changes

2016-10-11 10:18 UTC, rakvium commented on app/controllers/registrations_controller.rb
> +    params.require(:driver).permit(:email, :password, :password_confirmation, :current_pussword, :name, :phone_number_string, :license_plate, :car_model, :car_color, :car_type, :upload => [:tempfile,
`current_pussword`? `pussword`? Seriously?

2016-10-11 11:29 UTC, rakvium requested changes

2016-10-11 11:29 UTC, rakvium commented on app/models/ability.rb
> +    user ||= User.new # guest user (not logged in)
You have no User model in the project :confused:

2016-10-11 11:32 UTC, bhkhdh commented on app/models/ability.rb
> +    user ||= User.new # guest user (not logged in)
It's fixed if branch "cancancan"

2016-10-11 11:44 UTC, rakvium approved these changes

2016-10-11 11:44 UTC, merged