readme
rakvium/taxi pull request #7
Opened 2016-10-04 08:59 UTC by Merkrow

2016-10-04 18:32 UTC, Merkrow commented
dispatcher and driver authorization

2016-10-05 08:27 UTC, rakvium requested changes

2016-10-05 08:27 UTC, rakvium commented on README.rdoc
> +Contributors:
Please use [markup](https://guides.github.com/features/mastering-markdown/) to make a header.

2016-10-05 08:27 UTC, rakvium commented on README.rdoc
> +Merkrow
Please add your e-mail if it's suitable for you.

2016-10-07 12:18 UTC, rakvium commented
This pull request doesn't make sense now.

2016-10-07 12:18 UTC, closed without merging